"""initial schema

Revision ID: b78ef6e9af52
Revises: 
Create Date: 2026-04-12 20:09:47.121896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78ef6e9af52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'credit_card', 'brokerage', 'ira', name='account_type_enum'), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('claude_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('insight_type', sa.Enum('spending_pattern', 'goal_trajectory', 'savings_opportunity', 'anomaly', name='insight_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claude_insights_insight_date'), 'claude_insights', ['insight_date'], unique=False)
    op.create_index(op.f('ix_claude_insights_insight_type'), 'claude_insights', ['insight_type'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal_type', sa.Enum('balance_target', 'contribution_rate', 'spend_limit', 'portfolio_growth', 'custom', name='goal_type_enum'), nullable=False),
    sa.Column('metric_source', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('direction', sa.Enum('increase', 'decrease', 'maintain', name='goal_direction_enum'), nullable=False),
    sa.Column('cadence', sa.Enum('daily', 'weekly', 'monthly', name='goal_cadence_enum'), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('natebot_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'failed', name='goal_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_table('natebot_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_natebot_events_timestamp'), 'natebot_events', ['timestamp'], unique=False)
    op.create_table('balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_type', sa.Enum('cash', 'portfolio_value', name='balance_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_account_id'), 'balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_balances_balance_date'), 'balances', ['balance_date'], unique=False)
    op.create_table('goal_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_alerts_goal_id'), 'goal_alerts', ['goal_id'], unique=False)
    op.create_table('goal_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pct_complete', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_snapshots_goal_id'), 'goal_snapshots', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_snapshots_snapshot_date'), 'goal_snapshots', ['snapshot_date'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_holdings_snapshot_date'), 'holdings', ['snapshot_date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_fixed_expense', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id'),
    sa.UniqueConstraint('plaid_transaction_id', name='uq_transaction_plaid_id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_holdings_snapshot_date'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_goal_snapshots_snapshot_date'), table_name='goal_snapshots')
    op.drop_index(op.f('ix_goal_snapshots_goal_id'), table_name='goal_snapshots')
    op.drop_table('goal_snapshots')
    op.drop_index(op.f('ix_goal_alerts_goal_id'), table_name='goal_alerts')
    op.drop_table('goal_alerts')
    op.drop_index(op.f('ix_balances_balance_date'), table_name='balances')
    op.drop_index(op.f('ix_balances_account_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_natebot_events_timestamp'), table_name='natebot_events')
    op.drop_table('natebot_events')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_claude_insights_insight_type'), table_name='claude_insights')
    op.drop_index(op.f('ix_claude_insights_insight_date'), table_name='claude_insights')
    op.drop_table('claude_insights')
    op.drop_table('accounts')
    # ### end Alembic commands ###
